#@data/values
---
backman:
  image: "jamesclonk/backman:1.23.1"

  pod_security_policy:
    enabled: true  # generates a k8s pod-security-policy if enabled

  network_policy:
    enabled: false # generates a k8s network-policy if enabled
    namespace_labels:
      ingress: # namespace matchLabels for ingress-controller access
        namespace.kubernetes.io/name: "ingress-nginx"
      prometheus: # namespace matchLabels for prometheus access
        namespace.kubernetes.io/name: "prometheus"

  ingress:
    enabled: false # generates a k8s nginx ingress resource if enabled
    hostname: "" # hostname for k8s nginx ingress
    cert_manager_tls:
      enabled: false # requires cert-manager.io to be installed for ingress TLS support to be enabled
      cluster_issuer: "" # requires a cluster-issuer name if TLS is enabled

  username: "" # basic-auth username
  password: "" # basic-auth password

  storage:
    s3:
      region: "" # optional
      host: "" # s3 hostname
      key: "" # s3 access key
      secret: "" # s3 secret key

  # services require: name, type, credentials, schedule, timeout and retention
  services: []
  # see sample_values.yml for reference
  # service type 'postgres' requires credentials: hostname, port, database, username and password
  # service type 'mysql' requires credentials: hostname, port, database, username and password
  # service type 'mysql' requires credentials: uri
  # service type 'mysql' requires credentials: hostname, port and password
  # service type 'elasticsearch' requires credentials: host, username and password
