name: snyk periodic scan

on:
  schedule:
  - cron: '0 9 * * 1'

permissions:
  contents: read

jobs:
  snyk-periodic-container:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - name: run snyk to check docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@dc22abdbe8ec00e2a925256fef96f319ca5510ce
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: docker.io/jamesclonk/backman:latest
        sarif: true
        args: --policy-path=. --file=Dockerfile
    - name: upload results to github code scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif

  snyk-periodic-golang:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - name: run snyk to for golang vulnerabilities
      continue-on-error: true
      uses: snyk/actions/golang@dc22abdbe8ec00e2a925256fef96f319ca5510ce
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --policy-path=. --file=go.mod --sarif-file-output=snyk.sarif
    - name: upload results to github code scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
